import { Model } from '../../../mol-model/structure';
import { ParamDefinition as PD } from '../../../mol-util/param-definition';
import { CustomProperty } from '../../../mol-model-props/common/custom-property';
import { CustomModelProperty } from '../../../mol-model-props/common/custom-model-property';
import { SeqInfoModel } from '../../services/model/common.model';
type SequenceList = (SeqInfoModel | null)[] | undefined;
export declare function fromServer(ctx: CustomProperty.Context, model: Model, props: AntibodyColoringResidueProps): Promise<CustomProperty.Data<SequenceList>>;
export declare const AntibodyColoringResidueParams: {};
export type Params = typeof AntibodyColoringResidueParams;
export type AntibodyColoringResidueProps = PD.Values<Params>;
export declare const AntibodyColoringResidueProvider: CustomModelProperty.Provider<Params, SequenceList>;
export {};
