import { Model } from '../../../../mol-model/structure';
import { ParamDefinition as PD } from '../../../../mol-util/param-definition';
import { CustomProperty } from '../../../../mol-model-props/common/custom-property';
import { CustomModelProperty } from '../../../../mol-model-props/common/custom-model-property';
import { SequenceList } from '../util';
export declare function fromServer(ctx: CustomProperty.Context, model: Model, props: AntibodyColoringResidueProps): Promise<CustomProperty.Data<SequenceList>>;
export declare const AntibodyColoringResidueParams: {};
export type Params = typeof AntibodyColoringResidueParams;
export type AntibodyColoringResidueProps = PD.Values<Params>;
export declare const AntibodyColoringResidueNorthProvider: CustomModelProperty.Provider<Params, SequenceList>;
